name: Docker Image CI

on:
  push:
    branches: [ "master", "actions"]
  pull_request:
    branches: [ "master", "actions" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |-
        docker build . --file Dockerfile --tag ghcr.io/arche-noah/swagger-generator:latest
        docker push $_
